config/routes.rb
Webcomic::Application.routes.draw do

  namespace :admin do
    resources :comics do
      collection do
        get 'first'
        get 'latest'
      end
    end
  end

  resources :comics do
    collection do
      get 'first'
      get 'latest'
      get 'random'
    end
  end
  
  get 'tags', to: 'tags#index', as: :tags
  get 'tags/:tag', to: 'comics#index', as: :tag
  get 'admin_tags/:tag', to: 'admin/comics#index', as: :admin_tag
  
  match '/feed' => 'comics#feed',
    :as => :feed,
    :defaults => { :format => 'atom' }

  devise_for :users

  root :to => "comics#latest"
  
end

app/models/comic.rb
# == Schema Information
#
# Table name: comics
#
#  id                 :integer          not null, primary key
#  title              :string(255)
#  description        :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#
class Comic < ActiveRecord::Base
  attr_accessible :description, :title, :image, :tag_list, :tooltip
  acts_as_taggable
  
  has_attached_file :image, 
    :styles => { :large => "600x600", :medium => "300x300>", :thumb => "100x100>" },
    :default_style => :large
  
  def next
    Comic.where("created_at > ?", created_at).order("created_at ASC").first
  end
  
  def next?
    !Comic.where("created_at > ?", created_at).order("created_at ASC").empty?
  end
  
  def prev
    Comic.where("created_at < ?", created_at).order("created_at ASC").last
  end
  
  def prev?
    !Comic.where("created_at < ?", created_at).order("created_at ASC").empty?
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/comics_controller.rb
class Admin::ComicsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction
  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.order("#{sort_column} #{sort_direction}").paginate(:page => params[:page], :per_page => params[:page_size]||10)
    
    if params[:tag]
      @comics = @comics.tagged_with(params[:tag])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comics }
    end
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
    @comic = Comic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comic }
    end
  end

  # GET /comics/new
  # GET /comics/new.json
  def new
    @comic = Comic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comic }
    end
  end

  # GET /comics/1/edit
  def edit
    @comic = Comic.find(params[:id])
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(params[:comic])

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render json: @comic, status: :created, location: @comic }
      else
        format.html { render action: "new" }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comics/1
  # PUT /comics/1.json
  def update
    @comic = Comic.find(params[:id])

    respond_to do |format|
      if @comic.update_attributes(params[:comic])
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /comics/first
  # GET /comics/first.json
  def first
    @comic = Comic.order("created_at ASC").first
    respond_to do |format|
      format.html { render 'show' }
      format.json { render json: @comic }
    end
  end

  # GET /comics/latest
  # GET /comics/latest.json
  def latest
    @comic = Comic.order("created_at ASC").last
    respond_to do |format|
      format.html { render 'show' }
      format.json { render json: @comic }
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic = Comic.find(params[:id])
    @comic.destroy

    respond_to do |format|
      format.html { redirect_to admin_comics_path }
      format.json { head :no_content }
    end
  end

  private
  def sort_column
    Comic.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  helper_method :sort_column, :sort_direction
  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.order("#{sort_column} #{sort_direction}").paginate(:page => params[:page], :per_page => params[:page_size]||10)
    
    if params[:tag]
      @comics = @comics.tagged_with(params[:tag])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comics }
    end
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
    @comic = Comic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comic }
    end
  end
  # GET /comics/first
  # GET /comics/first.json
  def first
    @comic = Comic.order("created_at ASC").first
    respond_to do |format|
      format.html { render 'show' }
      format.json { render json: @comic }
    end
  end

  # GET /comics/latest
  # GET /comics/latest.json
  def latest
    @comic = Comic.order("created_at ASC").last
    respond_to do |format|
      format.html { render 'show' }
      format.json { render json: @comic }
    end
  end
  
  def random
    offset = rand(Comic.count)
    @comic = Comic.first(:offset => offset)
    respond_to do |format|
      format.html { render 'show' }
      format.json { render json: @comic }
    end
  end
  
  def feed
    # this will be the name of the feed displayed on the feed reader
    # TODO add database driven title
    @title = "Webcomic"

    # the news items
    @comics = Comic.order("updated_at desc")

    # this will be our Feed's update timestamp
    @updated = @comics.first.updated_at unless @comics.empty?

    respond_to do |format|
      format.atom { render :layout => false }

      # we want the RSS feed to redirect permanently to the ATOM feed
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end

  private
  def sort_column
    Comic.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    controller.class.name.split("::").first=="Admin"
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to "#{title} #{icon_sort(column)}".html_safe, {:sort => column, :direction => direction}, {:class => css_class}
  end

  def icon_sort(column)
    if sort_column == column
      if sort_direction == "asc"
        "<i class=\"iconic-arrow-up\"> </i>"
      else
        "<i class=\"iconic-arrow-down\"> </i>"
      end
    end
  end
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/admin/comics/_form.html.erb
<%= form_for [:admin, @comic] do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows=>3, :class=>"span5" %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :tooltip, "Tooltip" %><br />
    <%= f.text_field :tooltip %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= image_tag @comic.image.url() if @comic.image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="form-actions">
    <%= f.submit "Create", {:class=>"btn btn-primary"} %>
    <%= link_to 'Back', admin_comics_path, :class=>"btn" %>
  </div>
<% end %>

app/views/admin/comics/_nav.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav">
      <li><%= link_to "First", first_admin_comics_path %></li>
      <li class="divider-vertical"></li>
      <li class="<%= "disabled" if !@comic.prev?%>"><%= link_to "Previous", @comic.prev %></li>
      <li class="divider-vertical"></li>
      <li><%=  link_to "Archive", comics_path %></li>
      <li class="divider-vertical"></li>
      <li class="<%= "disabled" if !@comic.next?%>"><%= link_to "Next", @comic.next %></li>
      <li class="divider-vertical"></li>
      <li><%= link_to "Latest", latest_admin_comics_path %></li>
    </ul>
  </div>
</div>

app/views/admin/comics/edit.html.erb
<h1>Editing comic</h1>

<%= render 'form' %>

app/views/admin/comics/index.html.erb
<h1>Listing comics</h1>

<div class="span6">
<table class="table table-striped">
  <tr>
    <th><%= sortable("title") %></th>
    <th><%= sortable("description") %></th>
    <th><%= sortable("created_at","Published") %></th>
    <th></th>
  </tr>

<% @comics.each do |comic| %>
  <tr>
    <td><%= comic.title.first(20) %></td>
    <td><%= comic.description.first(20) %></td>
    <td><%= comic.created_at.in_time_zone("EST").strftime("%b-%d-%y") %></td>
    <td><%= link_to 'View', admin_comic_path(comic), :class=>"btn btn-info" %>
    <%= link_to 'Edit', edit_admin_comic_path(comic), :class=>"btn btn-warning" %>
    <%= link_to 'Destroy', admin_comic_path(comic), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %></td>
  </tr>
<% end %>
</table>
<div>
  <%= will_paginate @comics %>
</div>
</div>
<br />

<%= link_to 'New Comic', new_admin_comic_path, :class=>"btn btn-primary" %>

app/views/admin/comics/new.html.erb
<h1>New comic</h1>

<%= render 'form' %>

app/views/admin/comics/show.html.erb
<div class="page-header">
  <h1><%= @comic.title %></h1>
  <%= @comic.created_at.in_time_zone("EST").strftime("%B %d %Y - %H:%M") %>
</div>

<%= render 'nav' %>

<div class="comic">
  <%= image_tag @comic.image.url(), :rel => "tooltip", :title => @comic.tooltip %>
</div>
<div class="description">
  <p><%= @comic.description %></p>
</div>
<div class="tags">
  <%= raw @comic.tag_list.map { |t| link_to t, tag_path(t), :class => "tag btn" }.join('') %>
</div>
<br/>
<br/>

<%= render 'nav' %>

app/views/comics/_form.html.erb
<%= form_for(@comic) do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows=>3, :class=>"span5" %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= image_tag @comic.image.url() if @comic.image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="form-actions">
    <%= f.submit "Create", {:class=>"btn btn-primary"} %>
    <%= link_to 'Back', comics_path, :class=>"btn" %>
  </div>
<% end %>

app/views/comics/_lower_nav.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav">
      <li>
        <%= link_to feed_path, :rel => "tooltip", :title => "atom feed" do %>
          <i class="icon-rss"></i>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to "http://www.reddit.com/submit?url=#{comic_url(@comic)}", :rel => "tooltip", :title => "submit to reddit" do %>
          <i class="icon-reddit"></i>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to "http://www.facebook.com/sharer.php?u=#{comic_url(@comic)}", :rel => "tooltip", :title => "share on facebook" do %>
          <i class="icon-facebook"></i>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to "http://twitter.com/share?text=An%20Awesome%20Link&url=#{comic_url(@comic)}", :rel => "tooltip", :title => "tweet" do %>
          <i class="icon-twitter"></i>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to "http://www.pinterest.com/pin/create/button/?url=#{comic_url(@comic)}", :rel => "tooltip", :title => "pin it" do %>
          <i class="icon-pinterest"></i>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to "https://plus.google.com/share?url=#{comic_url(@comic)}", :rel => "tooltip", :title => "share on google+" do %>
          <i class="icon-google-plus"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/comics/_nav.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav">
      <li>
        <%= link_to first_comics_path, :rel => "tooltip", :title => "first comic" do %>
          <i class="iconic-first"></i>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
      <li class="<%= "disabled" if !@comic.prev?%>">
        <%= link_to @comic.prev, :rel => "tooltip", :title => "previous comic" do %>
          <i class="icon-backward"></i>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to comics_path, :rel => "tooltip", :title => "comic archive" do %>
          <i class="icon-th-list"></i>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to random_comics_path, :rel => "tooltip", :title => "random comic" do %>
          <i class="icon-random"></i>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
      <li class="<%= "disabled" if !@comic.next?%>">
        <%= link_to @comic.next, :rel => "tooltip", :title => "next comic" do %>
          <i class="icon-forward"></i>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to latest_comics_path, :rel => "tooltip", :title => "latest comic" do %>
          <i class="iconic-last"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/comics/index.html.erb
<h1>Listing comics</h1>

<table class="table table-striped">
  <tr>
    <th><%= sortable("title") %></th>
    <th><%= sortable("description") %></th>
    <th><%= sortable("created_at","Published") %></th>
    <th></th>
  </tr>

<% @comics.each do |comic| %>
  <tr>
    <td><%= comic.title.first(20) %></td>
    <td><%= comic.description.first(20) %></td>
    <td><%= comic.created_at.in_time_zone("EST").strftime("%b-%d-%y") %></td>
    <td><%= link_to 'View', comic, :class=>"btn btn-info" %></td>
  </tr>
<% end %>
</table>
<div>
  <%= will_paginate @comics %>
</div>

app/views/comics/show.html.erb
<div class="page-header">
  <h1><%= @comic.title %></h1>
  <%= @comic.created_at.in_time_zone("EST").strftime("%B %d %Y - %H:%M") %>
</div>

<%= render 'nav' %>

<div class="comic">
	<%= image_tag @comic.image.url(), :rel => "tooltip", :title => @comic.tooltip %>
</div>
<div class="description">
  <%= @comic.description %>
</div>
<div class="tags">
  <%= raw @comic.tag_list.map { |t| link_to t, tag_path(t), :class => "tag act" }.join('') %>
</div>
<br/>
<br/>

<%= render 'lower_nav' %>
<%= render 'nav' %>

app/views/layouts/_top_bar.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <!-- TODO: Probably break this out into a seperate template. Likely to escalate.. quickly -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <!-- Main site link -->
      <%=link_to "Webcomic", root_path, :class=>"brand"%>
      <!-- Main site link end -->
      <!-- Site nav -->
      <div class="nav-collapse collapse">
        <!-- Controllers with direct menu links -->
        <ul class="nav">
          <li class="<%= "active" if controller_name == "comics" && !admin?%>"><%= link_to "Comics", comics_path %></li>
          <% if current_user %>
              <li class="<%= "active" if controller_name == "comics" && admin?%>"><%= link_to "Admin", admin_comics_path %></li>
              <li class="<%= "active" if controller_name == "comics" && admin?%>"><%= link_to "Log Out", destroy_user_session_path %></li>
          <% end %>
        </ul>

      </div>
      <!-- Site nav end -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- TODO: Make all reference to title DB driven, so this is easily deployable as OSS? -->
  <title>Webcomic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script>
      $.noConflict();
  </script>
  <%= auto_discovery_link_tag :atom, "/feed" %>
  <%= auto_discovery_link_tag :rss, "/feed.rss" %>
</head>
<body>
    <%= render :partial => "layouts/top_bar" %>
    <div class="container">
        <div class="span3 visible-desktop">
          <!-- left spacer, desktop only -->
        </div>
        <div class="span6">
            <p class="notice"><%= notice %></p>
            <% if alert %>
                <p class="alert"><%= alert %></p>
            <% end %>
            <%= yield %>
        </div>
        <div class="span3 visible-desktop">
          <!-- right spacer, desktop only -->
        </div>
    </div>
</body>
</html>

app/views/tags/index.html.erb
<% first = " " %>
<% tag_cloud Comic.tag_counts.sort { |x, y| x.name <=> y.name }, %w(x-small small normal large x-large) do |tag, css_class| %>
  <% unless tag.name.starts_with?(first) %>
    <br/><h3><%= tag.name[0] %></h3>
  <% end %>
  <% first = tag.name[0] %>
  <%= link_to tag.name, tag_url( :tag => tag.name ), :class => css_class+" btn tag" %>
<% end %>